# Generated by Django 5.1.7 on 2025-03-24 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='work_end',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='work_start',
        ),
        migrations.AddField(
            model_name='worker',
            name='work_end_hour',
            field=models.PositiveIntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='worker',
            name='work_start_hour',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
