# Generated by Django 5.1.7 on 2025-03-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_worker_work_end_remove_worker_work_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(default=234981234, max_length=255),
            preserve_default=False,
        ),
    ]
