# Generated by Django 5.1.7 on 2025-05-01 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_rename_first_name_customer_name_and_more'),
        ('warehouse', '0003_aisle_dock_payloadarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.driver'),
        ),
        migrations.AlterField(
            model_name='package',
            name='payload_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.payloadarea'),
        ),
        migrations.AlterField(
            model_name='package',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.truck'),
        ),
    ]
