# Generated by Django 5.1.7 on 2025-05-01 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_driver_alter_package_payload_area_and_more'),
        ('warehouse', '0003_aisle_dock_payloadarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
            preserve_default=False,
        ),
    ]
