# Generated by Django 5.1.7 on 2025-05-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_worker_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('at_dock', 'At dock'), ('in_preparation', 'In preparation'), ('ready_to_ship', 'Ready to ship'), ('on_the_way', 'On the way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='in_preparation', max_length=255),
        ),
    ]
