# Generated by Django 5.1.7 on 2025-05-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='packages',
            field=models.ManyToManyField(blank=True, to='delivery.package'),
        ),
    ]
