# Generated by Django 5.1.7 on 2025-05-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_delivery_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='payload_type',
            field=models.CharField(choices=[('food', 'Food'), ('drinks', 'Drinks'), ('rtv', 'RTV'), ('agd', 'AGD'), ('electronics', 'Electronics'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
