# Generated by Django 5.1.7 on 2025-05-01 19:06

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+48123987324', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
